In [57]:
import numpy as np

In [58]:
a=[1,2,3,4]
b=[5,6,7,8]
a+b


[1, 2, 3, 4, 5, 6, 7, 8]

In [59]:
a=[1,2,3,4]
b=[5,6,7,8]
[a[i] + b[i] for i in range(len(a))]

[6, 8, 10, 12]

In [60]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [61]:
arr=np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])
arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
arr[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [63]:
arr[2:,2:]

array([[10, 11]])

In [64]:
arr[3:,3:]

array([], shape=(0, 1), dtype=int64)

In [65]:
arr[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
arr[:,:1]

array([[1],
       [4],
       [8]])

In [67]:
arr[:,1:2]

array([[2],
       [5],
       [9]])

In [68]:
arr[:,2:3]

array([[ 3],
       [ 6],
       [10]])

In [69]:
arr[:,3:4]

array([[ 4],
       [ 7],
       [11]])

In [70]:
arr[2:,3:]

array([[11]])

In [71]:
arr[:1,:1]

array([[1]])

In [72]:
arr[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [73]:
arr[1:,[0,3]]

array([[ 4,  7],
       [ 8, 11]])

In [74]:
a=np.arange(10)

In [75]:
np.linspace(0,11,5)

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [76]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [77]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [78]:
a=np.array([1,2,3,4])
a*2

array([2, 4, 6, 8])

In [79]:
a**2

array([ 1,  4,  9, 16])

In [80]:
np.dot(a,b)

70

In [81]:
a=np.array([[1,2],[3,4]])
b=np.array([1,2,3])
a*b #dimension not same


ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [ ]:
a.T


In [ ]:
np.linalg.inv(a)

In [ ]:
np.linalg.det(a)

In [ ]:
a=[1,2,3,4]
b=[5,6,7,8]
np.hstack((a,b))

In [ ]:
np.vstack((a,b))

In [ ]:
np.unstack((a))

In [92]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [87]:
np.reshape(a,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
b=np.resize(a,(4,4))

In [90]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11,  1],
       [ 2,  3,  4,  5]])

In [93]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [94]:
import numpy as np
a = np.array((1,2,3))
b = np.array((4,5,6))
np.dstack((a,b))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [95]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])


In [104]:
b=a.view()

In [105]:
c=a.copy()

In [106]:
a,c


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [107]:
c[0]=11

In [108]:
a ,c


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [111]:
arr=np.array([[1,2,3],[4,5,6],[8,9,10]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [114]:
np.sum(arr,axis=1)

array([ 6, 15, 27])

In [115]:
def mean(arr):
    n=len(arr)
    return np.sum(arr)/n

In [117]:
mean(np.array([1,2,3,4,5,6]))

3.5

In [120]:
def variance(array):
    m=mean(array)
    n=len(array)
    return np.sum((array-m)**2)/n

In [122]:
variance(np.array([1,2,3,4,5,6]))

2.9166666666666665

In [131]:
def std(array):
    v=variance(array)
    return np.sqrt(v)

In [132]:
std(np.array([1,2,3,4,5,6]))

1.707825127659933

In [160]:
#sigmoid (1/1+e^-x)
#relu both activation functions max(0,x) kept 0 for nrgative values will get +ve values from relu
# min max scalar (x-xmin)/(xmax-xmin)
#standard scalar ((x-u)/variance)

In [161]:
def minmax(array):
    a=np.array([1,2,3,4,5,6])
    xmin=np.min(a)
    xmax=np.max(a)
    result=((a-xmin)/(xmax-xmin))
    return result

In [162]:
minmax(np.array([1,2,3,4,5,6]))

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [163]:
def ss(array):
     m=mean(a)
     v=variance(a)
     ss=(a-m/np.sqrt(v))
     return ss

In [164]:
ss(np.array([1,2,3,4,5,6]))

array([-1.04939015, -0.04939015,  0.95060985,  1.95060985,  2.95060985,
        3.95060985])

In [168]:
import numpy as np

def r(x):
    x = np.array(x)
    y= np.maximum(0, x)
    return y


In [169]:
r(np.array([1,2,3,4,5,6]))

array([1, 2, 3, 4, 5, 6])

In [170]:
def sigmoid(x):
    y=1 / (1 + np.exp(-x))
    return y

In [171]:
sigmoid(np.array([1,2,3,4,5,6]))

array([0.73105858, 0.88079708, 0.95257413, 0.98201379, 0.99330715,
       0.99752738])

In [ ]:
#leaky relu,mean square error,rmse